version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "test", "test/app.e2e-spec.ts"]
    environment:
      NODE_ENV: "development"
      RABBITMQ_URI: "amqp://rabbitmq"
      EMAIL_HOST: "mailhog"
      EMAIL_PORT: 1025
      EMAIL_USER: "anyuser"
      EMAIL_PASS: "anypass"
      SESSION_EXPIRY_MINUTES: 3600
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
      REDIS_URL: "redis://redis:6379"
