pipeline {
    agent any


    stages {
        stage('Checkout') {
            steps {
                git branch: 'dev', url: 'https://github.com/rickymal/aprove-me'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'docker-compose -f docker-compose.yml run --rm app npm install'
            }
        }
        stage('Generate Prisma') {
            steps {
                sh 'docker-compose -f docker-compose.yml run --rm app npx prisma generate'
            }
        }
        stage('Run Migrations') {
            steps {
                sh 'docker-compose -f docker-compose.yml run --rm app npx prisma migrate deploy'
            }
        }
        stage('Test') {
            steps {
                sh 'docker-compose -f docker-compose.yml run --rm app npm run test'
            }
        }
        // stage('Lint') {
        //     steps {
        //         sh 'docker-compose -f docker-compose.yml run --rm app npm run lint'
        //     }
        // }
        stage('Build') {
            steps {
                sh 'docker-compose -f docker-compose.yml run --rm app npm run build'
            }
        }
    }

    post {
        always {
            sh 'docker-compose -f docker-compose.yml down'
            cleanWs()
        }
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
