pipeline {
    agent any

    environment {
        DOCKER_COMPOSE_PATH = './backend/docker-compose.test.yml'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'dev', url: 'https://github.com/rickymal/aprove-me'
            }
        }
        stage('List Files') {
            steps {
                script {
                    // Lista os arquivos no workspace atual
                    sh 'ls -la'
                    sh 'ls -la backend'
                }
            }
        }
        stage('Install Dependencies and Test') {
            steps {
                script {
                    // Verifica se o package.json está presente
                    sh 'test -f backend/package.json'

                    // Executa os comandos docker-compose no diretório correto
                    sh 'docker-compose -f $DOCKER_COMPOSE_PATH build'
                    sh 'docker-compose -f $DOCKER_COMPOSE_PATH up -d'

                    // Adiciona um passo de debug para verificar os arquivos no contêiner
                    sh 'docker exec $(docker ps -q -f "name=backend_app") ls -la /app'
                }
            }
        }
    }

    post {
        always {
            script {
                // Derruba os containers
                sh 'docker-compose -f $DOCKER_COMPOSE_PATH down'
            }
        }
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
